#!/bin/sh
exec tail -n +3 $0
# This file provides an easy way to add custom menu entries.  Simply type the
# menu entries you want to add after this comment.  Be careful not to change
# the 'exec tail' line above.
menuentry "Linux Mint :)"{
set isoFile="/home/aekurekci/linuxmint-19.1-cinnamon-64bit.iso"
loopback loop (hd0,1)$isoFile
linux (loop)/casper/vmlinuz boot=casper iso-scan/filename=$isoFile noprompt noeject toram --
initrd (loop)/casper/initrd.lz
}
